version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'djangomodel'
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
      - ./mysqllogs:/logs
    ports:
      - '3306:3306'
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /root/DjangoModel/app01/static:/code/app01/static
    ports:
      - '8000:8000'
    depends_on:
      - db